"use strict";

const BOARDS = Object.freeze([
  { id: "everyday", name: "Everyday essentials", cards: [
    ["yes", "✓", "Yes", "answers", "#dff5e1"], ["no", "×", "No", "answers", "#ffe2e2"], ["help", "!", "Help", "needs", "#fff0c2"], ["please", "PLS", "Please", "conversation", "#e7ddff"], ["thanks", "♥", "Thank you", "conversation", "#ffe6ef"], ["more", "+", "More", "actions", "#e1f2ef"], ["finished", "✓", "Finished", "actions", "#e5f0ff"], ["wait", "…", "Wait", "actions", "#e5e8ec"], ["water", "W", "Water", "needs", "#dcecff"], ["food", "F", "Food", "needs", "#ffe8cf"], ["toilet", "T", "Toilet", "needs", "#e7ddff"], ["rest", "Zzz", "I need rest", "needs", "#e1eaf5"], ["cold", "COLD", "I feel cold", "comfort", "#dcecff"], ["hot", "HOT", "I feel hot", "comfort", "#fff0c2"], ["quiet", "SHH", "I need quiet", "comfort", "#e5e8f4"], ["different", "?", "Something different", "conversation", "#ececec"]
  ]},
  { id: "feelings", name: "Feelings & comfort", cards: [
    ["happy", ":)", "I feel good", "feelings", "#fff5b8"], ["sad", ":(", "I feel sad", "feelings", "#dfe8ff"], ["worried", "!", "I feel worried", "feelings", "#ffe6c7"], ["angry", "!", "I feel angry", "feelings", "#ffd9d9"], ["scared", "!", "I feel scared", "feelings", "#eadfff"], ["tired", "Zzz", "I feel tired", "feelings", "#e1eaf5"], ["pain", "P", "I am in pain", "health", "#ffd9d9"], ["better", "↑", "I feel better", "health", "#dff5e1"], ["break", "||", "I need a break", "comfort", "#e7f2ff"], ["hug", "♥", "I want comfort", "comfort", "#ffe6ef"], ["alone", "1", "I want to be alone", "comfort", "#e8e8f2"], ["together", "2", "Stay with me", "comfort", "#e1f2ef"], ["cold", "COLD", "I feel cold", "comfort", "#dcecff"], ["hot", "HOT", "I feel hot", "comfort", "#fff0c2"], ["quiet", "SHH", "It is too loud", "comfort", "#e5e8f4"], ["safe", "OK", "I feel safe", "feelings", "#dff5e1"]
  ]},
  { id: "conversation", name: "Conversation & choices", cards: [
    ["hello", "HI", "Hello", "conversation", "#dcecff"], ["goodbye", "BYE", "Goodbye", "conversation", "#e7ddff"], ["again", "↻", "Please say that again", "conversation", "#e8e8e8"], ["understand", "OK", "I understand", "conversation", "#dff5e1"], ["confused", "?", "I do not understand", "conversation", "#fff0c2"], ["look", "LOOK", "Please look at me", "conversation", "#e5f0ff"], ["listen", "EAR", "Please listen", "conversation", "#e1f2ef"], ["slow", "SLOW", "Please go slowly", "conversation", "#ffe8cf"], ["write", "ABC", "Please write it down", "conversation", "#e7ddff"], ["choose", "?", "I want to choose", "choices", "#fff5b8"], ["this", "THIS", "This one", "choices", "#dcecff"], ["that", "THAT", "That one", "choices", "#e1f2ef"], ["not-sure", "?", "I am not sure", "choices", "#ffe8cf"], ["stop", "STOP", "Please stop", "choices", "#ffd9d9"], ["continue", "GO", "Please continue", "choices", "#dff5e1"], ["call", "☎", "Please call someone", "conversation", "#e5f0ff"]
  ]},
  { id: "care", name: "Care & health words", cards: [
    ["pain", "P", "I am in pain", "health", "#ffd9d9"], ["head", "HEAD", "My head hurts", "health", "#ffe2e2"], ["stomach", "STOM", "My stomach hurts", "health", "#ffe8cf"], ["medicine", "MED", "I need my medicine", "health", "#e7ddff"], ["doctor", "DR", "I want a doctor", "health", "#e5f0ff"], ["nurse", "NURSE", "I want a nurse", "health", "#dcecff"], ["water", "W", "I need water", "needs", "#dcecff"], ["food", "F", "I need food", "needs", "#ffe8cf"], ["toilet", "T", "I need the toilet", "needs", "#e7ddff"], ["rest", "Zzz", "I need to rest", "needs", "#e1eaf5"], ["cold", "COLD", "I feel cold", "comfort", "#dcecff"], ["hot", "HOT", "I feel hot", "comfort", "#fff0c2"], ["breathe", "AIR", "Help me breathe slowly", "health", "#e1f2ef"], ["hurt", "!", "Something hurts", "health", "#ffd9d9"], ["better", "↑", "I feel better", "health", "#dff5e1"], ["emergency", "!", "This feels urgent", "health", "#ffcaca"]
  ]}
].map((board) => ({ ...board, cards: board.cards.map(([id, symbol, label, category, color]) => ({ id, symbol, label, category, color })) })));

const state = { board: BOARDS[0] };
const $ = (id) => document.getElementById(id);
function setStatus(text, error = false) { $("status").textContent = text; $("status").classList.toggle("error", error); }
function renderBoards() { const select = $("board-select"); select.replaceChildren(...BOARDS.map((board) => { const option = document.createElement("option"); option.value = board.id; option.textContent = `${board.name} (${board.cards.length} cards)`; return option; })); select.value = state.board.id; }
function renderBoard() { $("active-board-name").textContent = state.board.name; document.title = `${state.board.name} — OpenVoice Board`; const grid = $("board-grid"); grid.replaceChildren(); grid.setAttribute("aria-busy", "false"); state.board.cards.forEach((card) => { const button = document.createElement("button"); button.type = "button"; button.className = "card-button"; button.style.backgroundColor = card.color; button.setAttribute("aria-label", `Speak ${card.label}`); const symbol = document.createElement("span"); symbol.className = "card-symbol"; symbol.setAttribute("aria-hidden", "true"); symbol.textContent = card.symbol; const label = document.createElement("span"); label.className = "card-label"; label.textContent = card.label; const category = document.createElement("span"); category.className = "card-category"; category.textContent = card.category; button.append(symbol, label, category); button.addEventListener("click", () => speak(card.label)); grid.append(button); }); }
function speak(text) { if (!("speechSynthesis" in window) || !("SpeechSynthesisUtterance" in window)) return setStatus("Speech playback is not supported; the visual message still works.", true); window.speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(text); utterance.rate = Number($("speech-rate").value); utterance.lang = document.documentElement.lang || "en"; window.speechSynthesis.speak(utterance); }
$("board-select").addEventListener("change", (event) => { state.board = BOARDS.find((board) => board.id === event.target.value) || BOARDS[0]; renderBoard(); setStatus("Board changed. Tap a card to hear its phrase."); });
$("print-board").addEventListener("click", () => window.print());
$("contrast-toggle").addEventListener("click", () => { const on = document.body.classList.toggle("high-contrast"); $("contrast-toggle").setAttribute("aria-pressed", String(on)); });
$("speech-rate").addEventListener("input", (event) => { $("rate-output").value = `${Number(event.target.value).toFixed(1)}×`; });
renderBoards(); renderBoard(); setStatus("Ready. Tap a card to hear its phrase.");
